name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag rec-web3-atarca-flask
    - name: Docker Registry Login
      run: echo "${{DOCKER_PASSWORD}}" | docker login -u ${{DOCKER_USERNAME}} --password-stdin ${{DOCKER_REGISTRY}}
    - name: Upload Docker image to Registry
      run: docker push rec-web3-atarca-flask
